### ISSUE TITLE
DNS over LAN is not working on windows and linux

### ISSUE THREAD

**Issue by ben-en** [Outernet-Project/lighthouse-firmware#16]
All addresses (including librarian.outernet and outernetrx.lan) do not resolve.

A previous session opened to outernetrx.lan/en/dashboard in firefox seemed to work and claimed to be connected, but didnt actually render updated information or allow tuner settings to be set. Trying to use any links resulted in problem loading page errors.

Internet explorer will endlessly wait for a reply from outernetrx.lan after giving a couple of errors about not being connected to a network.

**Comment by foxbunny** [comment]
DNS is not supposed to work over LAN.
